export const ENVIRONMENT_VARIABLES = {
  VITE_EMAIL_PUBLIC_KEY: import.meta.env.VITE_EMAIL_PUBLIC_KEY,
  VITE_EMAIL_SERVICE_ID: import.meta.env.VITE_EMAIL_SERVICE_ID,
  VITE_EMAIL_TEMPLATE_ID: import.meta.env.VITE_EMAIL_TEMPLATE_ID,
};
